<?php

namespace Jus\SimpleBundle\Repository;

/**
 * AlphaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlphaRepository extends \Doctrine\ORM\EntityRepository
{
}
