<?php

namespace Jus\SimpleBundle\Repository;

/**
 * BetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BetaRepository extends \Doctrine\ORM\EntityRepository
{
}
