<?php

namespace Jus\SimpleBundle\Repository;

/**
 * GammaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GammaRepository extends \Doctrine\ORM\EntityRepository
{
}
